"""Integration tests for CHANGELOG.md generation."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pytest_copie.plugin import Copie


def test_changelog_generated_when_enabled(copie: Copie, base_answers: dict[str, str]) -> None:
    """Test that CHANGELOG.md is generated when with_changelog is True."""
    answers = {**base_answers, 'copyright_license': 'MIT', 'with_changelog': True}
    result = copie.copy(extra_answers=answers)

    assert result.exit_code == 0
    assert result.exception is None
    assert result.project_dir is not None

    changelog = result.project_dir / 'CHANGELOG.md'
    assert changelog.exists()


def test_changelog_not_generated_when_disabled(copie: Copie, base_answers: dict[str, str]) -> None:
    """Test that CHANGELOG.md is not generated when with_changelog is False."""
    answers = {**base_answers, 'copyright_license': 'MIT', 'with_changelog': False}
    result = copie.copy(extra_answers=answers)

    assert result.exit_code == 0
    assert result.exception is None
    assert result.project_dir is not None

    changelog = result.project_dir / 'CHANGELOG.md'
    assert not changelog.exists()


def test_changelog_default_enabled(copie: Copie, base_answers: dict[str, str]) -> None:
    """Test that CHANGELOG.md is generated by default (with_changelog defaults to True)."""
    answers = {**base_answers, 'copyright_license': 'MIT'}
    result = copie.copy(extra_answers=answers)

    assert result.exit_code == 0
    assert result.exception is None
    assert result.project_dir is not None

    changelog = result.project_dir / 'CHANGELOG.md'
    assert changelog.exists()


def test_changelog_content(copie: Copie, base_answers: dict[str, str]) -> None:
    """Test that CHANGELOG.md contains expected content."""
    answers = {**base_answers, 'copyright_license': 'MIT', 'with_changelog': True}
    result = copie.copy(extra_answers=answers)

    assert result.exit_code == 0
    assert result.project_dir is not None

    changelog = result.project_dir / 'CHANGELOG.md'
    content = changelog.read_text()
    assert '# Changelog' in content
    assert 'Keep a Changelog' in content
    assert 'Semantic Versioning' in content
    assert '## [Unreleased]' in content
