---
project_name:
  type: str
  help: "Name of this project:"
  default: "{{ _folder_name }}"
  validator: >-
    {% if not project_name %}
    Project name cannot be empty.
    {% endif %}

project_package:
  type: str
  help: "Package name of this project:"
  default: "{{ project_name.replace('-', '_') }}_lib"
  validator: >-
    {% if not (project_package | regex_search('^[a-zA-Z_][a-zA-Z0-9\_]*$')) %}
    Project package must start with a letter or underlines, followed one or more letters, digits or underlines.
    {% endif %}

  project_identifier:
    type: str
    help: "Identifier of this project:"
    default: "{{ project_name }}"
    validator: >-
      {% if not project_identifier %}
      Project identifier cannot be empty.
      {% endif %}

project_description:
  type: str
  help: "Description of this project:"
  placeholder: "New project generated via copier."
  validator: >-
    {% if not project_description %}
    Project description cannot be empty.
    {% endif %}
